### ISSUE TITLE
what will happens if a spatialRDD(called a) use method setSpatialPartitioning(),but the method’s argument is another SPatialRDD's(called b) Partitioner？

### ISSUE THREAD

**Issue by KingWang93** [DataSystemsLab/GeoSpark#184]
![image](https://user-images.githubusercontent.com/17794023/35714926-7df5bf30-080a-11e8-89a8-72342b6370a3.png)
As the title said,what will happens if a spatialRDD(called a) use method setSpatialPartitioning(),but the method’s argument is another SPatialRDD's(called b) Partitioner？especially when b's boundary is smaller than a's.
a's points out side of b's doundary will be filtered？if not filtered, then how does it work?

**Comment by jiayuasu** [comment]
Hi @KingWang93 ,

We must use the same partitioner to partition both datasets involved in Spatial Join.

If A's boundary is smaller than B but you still use A's partitioner to partition B, overflowed data of B will be put in an overflow partition. The overflow partition will be eliminated directly by the spatial join algorithm. Because it is guaranteed to have no qualified results.

**Comment by KingWang93** [comment]
overflow partition?what does it mean?it's just a concept or it is created by program?In addition，another problem，in GeometrySerde.java，why userData is not serialized when the geometry is Point,LineString, etc.？
`   
 @Override
    public void write(Kryo kryo, Output out, Object object) {
        if (object instanceof Circle) {
            Circle circle = (Circle) object;
            writeType(out, Type.CIRCLE);
            out.writeDouble(circle.getRadius());
            writeGeometry(kryo, out, circle.getCenterGeometry());
            writeUserData(kryo, out, circle);
        } else if (object instanceof Point || object instanceof LineString
            || object instanceof Polygon || object instanceof MultiPoint
            || object instanceof MultiLineString || object instanceof MultiPolygon) {
            writeType(out, Type.SHAPE);
            writeGeometry(kryo, out, (Geometry) object);
        } else if (object instanceof GeometryCollection) {
            GeometryCollection collection = (GeometryCollection) object;
            writeType(out, Type.GEOMETRYCOLLECTION);
            out.writeInt(collection.getNumGeometries());
            for (int i=0; i<collection.getNumGeometries(); i++) {
                writeGeometry(kryo, out, collection.getGeometryN(i));
            }
            writeUserData(kryo, out, collection);
        } else if( object instanceof Envelope) {
            Envelope envelope = (Envelope) object;
            writeType(out, Type.ENVELOPE);
            out.writeDouble(envelope.getMinX());
            out.writeDouble(envelope.getMaxX());
            out.writeDouble(envelope.getMinY());
            out.writeDouble(envelope.getMaxY());
        } else {
            throw new UnsupportedOperationException("Cannot serialize object of type " +
                object.getClass().getName());
        }
    }
`

**Comment by jiayuasu** [comment]
@KingWang93 
Basically, GeoSpark has two types of spatial partitioners. This is caused by GeoSpark's sampling technique and these data structure's features.

P1: Partitioners that fully cover the entire target space: KDB-Tree, Quad-Tree partitioner
P2: Partitioners that cannot fully cover the entire target space: R-Tree, Voronoi diagram, Hilbert curve partitioner

Say, RDD A and B both use A's partitioner P. We have a geometry G that doesn't fall in the spatial boundary of any partition.
If P is P1,  G will be filtered during spatial partitioning phase. Because it is guaranteed to be useless.

If P is P2, G will be allocated to an overflow partition during spatial partitioning phase. Overflow partition from A and B will be double checked during join phase to make sure we can find all overlapped geometry pairs.

If you go through GeoSpark's source code in SpatialPartitioning folder, you will figure out.

**Comment by KingWang93** [comment]
thanks for your detailed reply！A suggestion more for GeoSpark，when do an operation to detect the relationship bwtween a single target geometry and a batch of test geometries. Prepared geometry class in JTS will be fatser than Geometry class. It can be optimized in some class like RightIndexLookupJudgement,LeftIndexLookupJudgement etc.[https://trac.osgeo.org/geos/wiki/PreparedGeometry](url)

**Comment by jiayuasu** [comment]
@KingWang93 Thanks for your great suggestion. I didn't know that before. Will look into that.

**Comment by KingWang93** [comment]
when I look through the code, So it will be happen like this, when  a geometry doing spatialPartitioning , it will fall in two tree node region? how to guarantee that one geometry can't be computed twice?

**Comment by jiayuasu** [comment]
@KingWang93 

We have an extra step called duplicates removal.

For Partitioner P1, we use an idea called references point idea to remove the duplicates.

For Partitioner P2, we use an addition GroupBy (a data shuffle) to collect duplicated results and remove them.

We have a full research paper to introduce every single component of GeoSpark. We will release it very soon.
