### ISSUE TITLE
SPARK 2.0.1  java.lang.NoSuchMethodError 

### ISSUE THREAD

**Issue by Tsarazin** [DataSystemsLab/GeoSpark#22]
Hi everyone, I am using Spark 2.0.1, I added geospark to my project but when i run i get this error java.lang.NoSuchMethodError in every tests using parquet. Do you know why?

**Comment by jiayuasu** [comment]
Hi,

Thanks for your interest! 

The GeoSpark 0.3.1 in Maven Central is compiled with Spark 2.0.0. If this is the issue, you can download GeoSpark source code, change the POM easily and compile it with Spark 2.0.1. 

In fact, last week, Apache Spark 2.0.1 was not available at Maven central. That's why GeoSpark goes 2.0.0.

Thanks,
Jia

**Comment by jiayuasu** [comment]
Another much simpler method is that just change your Spark version to 2.0.0. Then you can use the Maven central GeoSpark.

**Comment by jiayuasu** [comment]
Hi,

I just updated GeoSpark in Maven Central. It now supports Spark 2.0.1.  It should be synced to all associated Maven storage space within several hours. Please let me know if bugs still exist.

Thanks,
Jia

**Comment by Tsarazin** [comment]
it's working! thanks a lot!
