### ISSUE TITLE
GeoSpark CRSTransform doesn't recognize ESPG4326 and ESPG3857

### ISSUE THREAD

**Issue by avshRepo** [DataSystemsLab/GeoSpark#290]
## Expected behavior
transform coordinates from WGS84 to meter based CRS

## Actual behavior
the function throws the following exception:
org.opengis.refenecing.NoSuchAuthorityCodeException:

## Steps to reproduce the problem
rdd.CRSTransform("epsg:4326", "epsg:3857")

## Settings

GeoSpark version =1.2.0

Apache Spark version = 2.3.0

JRE version = 1.8

API type = Scala

**Comment by jiayuasu** [comment]
@avshRepo This is because you didn't package all geotools package properly. Please make sure your fat jar contains all these geotools dependencies: https://github.com/DataSystemsLab/GeoSpark/blob/master/core/pom.xml#L52
By default, GeoSpark packages all of them already. But sometimes, some packaging software cannot make it correct.
