### ISSUE TITLE
Add GeoJsonReader.readToGeometryRDD example to the docs

### ISSUE THREAD

**Issue by netanel246** [DataSystemsLab/GeoSpark#309]
## Expected behavior
Example how to read geojson RDD as described [here](https://github.com/DataSystemsLab/GeoSpark/blob/34607225b82a5b490420138aff50739b02bbb8a6/sql/src/test/scala/org/datasyslab/geosparksql/constructorTestScala.scala#L81) just like the [shapefileReader](https://github.com/DataSystemsLab/GeoSpark/blob/b2b6f1d7f0015d5c9d663a7b28d5e1bb1043c413/docs/tutorial/rdd.md#L187)
## Settings

GeoSpark version = 1.2.0

Apache Spark version = ?

JRE version = 1.8?

API type = Scala or Java?

**Comment by ps-spark** [comment]
Thank you for the effort of writing such a great framework. There is really a big demand in the Spark community.

I have tried to set up a small example using the stable release based on the tutorial but there are several false information in it.
- GeoJsonReader does not exist in Maven central (org.datasyslab.geospark.formatMapper) under version 1.1.3
- GeoSparkSQL does not have the version 1.1.3 in Maven, only 1.1.1
- There is no JavaDoc for version 1.1.3 under http://www.public.asu.edu/~jiayu2/geospark/javadoc/ and version 1.1.2 does not conform with the Maven Repo.

It would be important to mention that the Tutorial is for the SNAPSHOT and not for the stable release. I wasted so much time, trying to figure out, what the problem is.

**Comment by jiayuasu** [comment]
@ps-spark 

1. All GeoSpark stable releases are hosted on Maven Central including GeoSparkSQL 1.1.3.
https://mvnrepository.com/search?q=geospark
Please make sure you use the correct Maven coordinate.

2. SNAPSHOT version can also be used directly in POM.xml or build.sbt
http://datasystemslab.github.io/GeoSpark/download/GeoSpark-All-Modules-Maven-Central-Coordinates/#snapshot-versions

3. GeoSpark-core 1.1.3 has the same API with 1.1.2. But thanks for reminding me.

4. I would suggest you use GeoJSONReader provided in 1.2.0-SNAPSHOT. Its API won't change and it is easier for you to use. BTW, thanks for your suggestion. I will figure out a way to include docs for different versions.
