### ISSUE TITLE
Spatial Geometric Difference Set

### ISSUE THREAD

**Issue by yangjiurong** [DataSystemsLab/GeoSpark#375]
hi jia, would geospark will provide spatial geometric difference set function or other spatial function in the future? such as st_difference ,st_symdifference, st_dump etc

if not provide , Is there any alternative? 

thanks

## Settings

GeoSpark version = 1.2.0

Apache Spark version = 2.3.0

JRE version = 1.8

API type =  Java

**Comment by jiayuasu** [comment]
@yangjiurong Hi we currently don't support that. But please note that, since GeoSpark internally uses JTS, JTS has basically implemented all these functions. If you are in a rush, you can write your own Spark UserDefinedFunction and simply write a single line code like this: https://github.com/DataSystemsLab/GeoSpark/blob/master/sql/src/main/scala/org/apache/spark/sql/geosparksql/expressions/Functions.scala#L285

**Comment by yangjiurong** [comment]
thank you for feedback , you giving me a direction to solve the problem. thank you very mach
