### ISSUE TITLE
Issue in running tests

### ISSUE THREAD

**Issue by uniysfu** [DataSystemsLab/GeoSpark#384]
## Expected behavior
I want to run the tests under core/src/test/java/
## Actual behavior
test return error when compiling, showing 
![image](https://user-images.githubusercontent.com/14852975/63820041-19ae4800-c98b-11e9-950b-9eecc7d9456b.png)

it seems the java compiler cannot find the Class GeoSparkMetric which is written in Scala

## Settings

GeoSpark version =  1.2.0?
Apache Spark version = ?

JRE version = 1.8?

API type = Scala or Java?

**Comment by uniysfu** [comment]
@jiayuasu

**Comment by d61-adrian** [comment]
Firstly ensure you are using java 8. Next run mvn install, profit.

**Comment by AntreasPetsas** [comment]
@uniysfu i resolved the problem yesterday. You must have java 8 on your pc. Ensure in Project Structure that (if you are using intellij) the JDK that you are using is the java oracle 8 instead of the default jdk of intellij. Second, if you are using windows you must add HADOOP_HOME in your system variables.
