### ISSUE TITLE
Spatial join does not find all points within polygon

### ISSUE THREAD

**Issue by john-min** [DataSystemsLab/GeoSpark#69]
The spatial join does not find all points within a set of polygons. 
I take the unmatched points,  and subsequently join them with the same polygons, and find more (incomplete) matches.

**Comment by jiayuasu** [comment]
Hi @john-min , thanks for letting me know. Recently I have received several reports from users. Trying to look into that. A new patch will be out very soon.

**Comment by jiayuasu** [comment]
The description of this bug is: In GeoSpark 0.5.2 and before, if two spatial objects have the same spatial coordinates but different non-spatial attributes (stored in UserData), GeoSpark think they are same and will only keep one object randomly.

This bug has been fixed in GeoSpark 0.5.3 and later. Duplicate spatial objects will be remove only if they have same spatial coordinates and non-spatial attribute (UserData).
