### ISSUE TITLE
WKT parsing problem in 0.6.1 version of geospark

### ISSUE THREAD

**Issue by geoHeil** [DataSystemsLab/GeoSpark#83]
With the latest updates from 0.6.1-snapshot to 0.6.1 release a bug was introduced regarding line string parsing. The error is: `LinearRing do not form a closed linestring`

To reproduce you can use the data from the Babylon showcase https://github.com/geoHeil/geoSparkScalaSample/tree/master/src/test/resources and run
```
git clone https://github.com/geoHeil/geoSparkScalaSample.git
cd geoSparkScalaSample
sbt run
# when propmpted for multiple main classes select 2 
```

**Comment by jiayuasu** [comment]
Hi @geoHeil , I have investigated the problem. This is not caused by GeoSpark. There is a typo in your code. It guides PolygonRDD to take a rectangle csv as inputLocation. Any Polygon CSV/TSV input require that, in each tuple, the last coordinate must be same with the first coordinate. 

In VisualizationGeosparkLocalRaster.scala, L50 - L53
```
  val RectangleOffset = prop.getProperty("offset").toInt
  val RectangleSplitter = FileDataSplitter.getFileDataSplitter(prop.getProperty("splitter"))
  val RectangleNumPartitions = prop.getProperty("numPartitions").toInt
  val PolygonInputLocation = "file://" + System.getProperty("user.dir") + "/" + resourcePath + prop.getProperty("inputLocation")
```

**Comment by geoHeil** [comment]
Sorry for that one. Indeed, you are right. I wonder what else could have changed with my real dataset.
