### ISSUE TITLE
Rectangle Join Test

### ISSUE THREAD

**Issue by missakation** [DataSystemsLab/GeoSpark#88]
I am trying to test the Rectangle Join Query but getting this errors here.

1: List<Tuple2<Polygon, HashSet<Polygon>>> result = 
 JoinQuery.SpatialJoinQuery(spatialRDD,queryRDD,false,true).collect();

**_The method SpatialJoinQuery(RectangleRDD, RectangleRDD, boolean) in the type JoinQuery is not applicable for the arguments (RectangleRDD, RectangleRDD, boolean, boolean)_**

2: When I remove one of the booleans:
_**Type mismatch: cannot convert from List<Tuple2<Envelope,HashSet<Envelope>>> to List<Tuple2<Polygon,HashSet<Polygon>>>**_

**Comment by jiayuasu** [comment]
Hi @missakation ,

The second solution is correct.
Not sure why you use Envelope in the result list, you should use Polygon in List instead.

To be compatible with standard geometry types, since GeoSpark 0.6.0, all RectangleRDD are internally treated as same as PolygonRDD. All rectangles are stored in polygon object.

Thanks,
Jia
