### ISSUE TITLE
Support 3D points

### ISSUE THREAD

**Issue by marcopinheiro** [DataSystemsLab/GeoSpark#92]
The Coordinate structure appears to support more then two dimensions. However, I saw RDD objects like PointRDD, and indexes works only in a two dimension world. Is it possible to use this package to 3D environment or would you like to recommend an alternative package?

My problem is to find the neighbor points for each point and then apply some custom function. But, there, points have 3 dimensions.

**Comment by jiayuasu** [comment]
@marcopinheiro Hi, currently GeoSpark doesn't not directly support 3d k nearest neighbor search. However, since GeoSpark is highly extendable, you are able to make GeoSpark support 3D KNN search through light modification.

Three steps are needed:

1. Load 3D point by using a GeoSpark customized data mapper

2. Change core KNN logic.
The core KNN logic is put here: https://github.com/DataSystemsLab/GeoSpark/tree/master/core/src/main/java/org/datasyslab/geospark/knnJudgement

You need to modify two files to support 3D euclidean distance calculation:
(1) https://github.com/DataSystemsLab/GeoSpark/blob/master/core/src/main/java/org/datasyslab/geospark/knnJudgement/KnnJudgement.java#L58
(2) The call function starts from https://github.com/DataSystemsLab/GeoSpark/blob/master/core/src/main/java/org/datasyslab/geospark/knnJudgement/GeometryDistanceComparator.java#42

3. Recompile GeoSpark

Please let me know if you want to know more details
