### ISSUE TITLE
EPSG coordinate system missing

### ISSUE THREAD

**Issue by geoHeil** [DataSystemsLab/GeoSpark#96]
I follow your example of using the coordinate system, but get the following error: `"EPSG:4326" from authority "EPSG" found for object of type "EngineeringCRS".`

**Comment by jiayuasu** [comment]
@geoHeil Which example are you referring to? What are the source and target CRS you are using?

**Comment by geoHeil** [comment]
Both the same (EPSG:4326) as in https://github.com/DataSystemsLab/GeoSpark/blob/master/core/src/main/scala/org/datasyslab/geospark/showcase/ScalaExample.scala#L221 I thought as we were not using any CRS it would be better to specify the projection as this is possible now.

**Comment by jiayuasu** [comment]
@geoHeil 
This error is not made by GeoSpark. It seems Geotools doesn't allow the source CSR is same with the target CRS.

Any degree based coordinates must be in a CRS. If you don't know the CRS in your data or you can tolerate the errors, you don't have to use CRS. Just keep using the old SRDD constructors. Everything remains the same.

**Comment by geoHeil** [comment]
Ok, if data is WGS-84 you say it makes no sense to specify a projection as outlined above as this will not increase accuracy and apparently Geotools will not allow the same origin / destination.

**Comment by jiayuasu** [comment]
@geoHeil You must know the target CRS before you transform the source CRS. No CRS is perfect so that you need to make the decision on your own. But obviously, meter-based target CRS will have better accuracy.

If your source data CRS is epsg:4326, you probably want to try to transform them to epsg:3857.
Please refer to: https://epsg.io/3857
